// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

////////////////////////////////////////////////////////////////////////////////////

// ! Deje las credenciales para pruebas y evitar problemas,
// ! espero que no me las roben :v

// ! Esto normalmente van ocultas en un archivo para variables de entorno
// ! aun no me familiarizo con eso en Flutter y son demaciadas credenciales

////////////////////////////////////////////////////////////////////////////////////

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALuHK-b2MRJV3jttVAcILOOp92ULiGhxE',
    appId: '1:285288498740:web:bf9e411bd370e04ee6ec61',
    messagingSenderId: '285288498740',
    projectId: 'regiscater',
    authDomain: 'regiscater.firebaseapp.com',
    storageBucket: 'regiscater.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnbgKXfS3j06Gn8TPBPTxWMk3GXVq4hWs',
    appId: '1:285288498740:android:565f3713e4a867b1e6ec61',
    messagingSenderId: '285288498740',
    projectId: 'regiscater',
    storageBucket: 'regiscater.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwaNndipLb_PsmJ57uFNWjS4mzimQkKw',
    appId: '1:285288498740:ios:66dea9c1a2c791a7e6ec61',
    messagingSenderId: '285288498740',
    projectId: 'regiscater',
    storageBucket: 'regiscater.appspot.com',
    iosClientId:
        '285288498740-vn9vhronhcpuebl5fgcnbl8jp6b910ko.apps.googleusercontent.com',
    iosBundleId: 'com.jose1060.regiscater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwaNndipLb_PsmJ57uFNWjS4mzimQkKw',
    appId: '1:285288498740:ios:66dea9c1a2c791a7e6ec61',
    messagingSenderId: '285288498740',
    projectId: 'regiscater',
    storageBucket: 'regiscater.appspot.com',
    iosClientId:
        '285288498740-vn9vhronhcpuebl5fgcnbl8jp6b910ko.apps.googleusercontent.com',
    iosBundleId: 'com.jose1060.regiscater',
  );
}
